// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrAwPKuZM-K_4Q6vZ6-R3nzR7Bxuc2jCo',
    appId: '1:1073912253938:web:a9cc4b2dab8fe3f17b2f6b',
    messagingSenderId: '1073912253938',
    projectId: 'chat-app-88c4a',
    authDomain: 'chat-app-88c4a.firebaseapp.com',
    storageBucket: 'chat-app-88c4a.appspot.com',
    measurementId: 'G-QC3FXN178Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgXaPRNp1GgBXtbZ4t0JuUTddSBqXntQ',
    appId: '1:1073912253938:android:5acaf30dbda4a0207b2f6b',
    messagingSenderId: '1073912253938',
    projectId: 'chat-app-88c4a',
    storageBucket: 'chat-app-88c4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLN3SHFhxzY93xHWvnYxwFWe5KrGcphrs',
    appId: '1:1073912253938:ios:c235882ea2f031fc7b2f6b',
    messagingSenderId: '1073912253938',
    projectId: 'chat-app-88c4a',
    storageBucket: 'chat-app-88c4a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLN3SHFhxzY93xHWvnYxwFWe5KrGcphrs',
    appId: '1:1073912253938:ios:c235882ea2f031fc7b2f6b',
    messagingSenderId: '1073912253938',
    projectId: 'chat-app-88c4a',
    storageBucket: 'chat-app-88c4a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrAwPKuZM-K_4Q6vZ6-R3nzR7Bxuc2jCo',
    appId: '1:1073912253938:web:07c3df5c34d377697b2f6b',
    messagingSenderId: '1073912253938',
    projectId: 'chat-app-88c4a',
    authDomain: 'chat-app-88c4a.firebaseapp.com',
    storageBucket: 'chat-app-88c4a.appspot.com',
    measurementId: 'G-490583M69S',
  );
}
